version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: src\HybridDb.sln
  verbosity: minimal
after_build:
- cmd: >-
    nuget install ILMerge -ExcludeVersion

    ILMerge\tools\ilmerge.exe /targetplatform:v4,C:\Windows\Microsoft.NET\Framework64\v4.0.30319 /target:library /internalize /out:HybridDb\HybridDb.dll bin\Release\HybridDb.dll bin\Release\Dapper.dll bin\Release\Newtonsoft.Json.dll bin\Release\Inflector.dll

    nuget pack HybridDb\HybridDb.nuspec -Version %APPVEYOR_BUILD_VERSION%
    nuget pack HybridDb.NewtonsoftJson\HybridDb.NewtonsoftJson.nuspec -Version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: rTAOxhsBekNlEb9IN6Iyy5mayYbiTTIWidYKB4f1ZyRbwiIeqjFr0x6qDZQM6RYP
services:
  - mssql2012sp1
